import type { DirectorySchoolAccount, SchoolDirectoryRaw, ZohoAccountStatus } from "@/types";
import { STATEWIDE_TOTAL_ZOHO_ACCOUNTS } from "@/lib/constants";
import { DISTRICT_SEEDS } from "./districts";
import { createRng, pick, randInt, shuffle } from "./prng";

/**
 * Builds the Zoho Classes Access directory from the real Tamil Nadu school
 * dataset (District name -> Block number -> school names). This is
 * intentionally decoupled from the procedural districts/blocks/schools
 * generated by geography-factory.ts (which still power the Education Map,
 * Alerts, and Overview) — those keep working unchanged via the existing
 * ZohoClassesAccount / assignedSchoolId lookup.
 */

const ENVIRONMENT_LABELS = [
  "Zoho Classes — TN State Board",
  "Zoho Classes — Matriculation Stream",
  "Zoho Classes — Primary Wing",
] as const;

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

function findDistrictId(districtName: string): string {
  const norm = districtName.trim().toLowerCase();
  const seed = DISTRICT_SEEDS.find((d) => d.name.toLowerCase() === norm);
  return seed?.id ?? slugify(districtName);
}

interface DirectorySlot {
  districtName: string;
  districtId: string;
  blockNumber: string;
  blockId: string;
  blockLabel: string;
  schoolName: string;
  schoolIndex: number;
}

/**
 * Selects ~totalAccounts schools from the raw directory, sampled round-robin
 * across districts (and, within a district, across its blocks via a
 * deterministic per-district shuffle) so the resulting Zoho account list has
 * broad District/Block filter coverage rather than being front-loaded from
 * whichever district happens to appear first in the JSON.
 */
export function buildDirectorySchoolAccounts(
  raw: SchoolDirectoryRaw,
  totalAccounts: number = STATEWIDE_TOTAL_ZOHO_ACCOUNTS,
): DirectorySchoolAccount[] {
  const perDistrictSlots: DirectorySlot[][] = Object.entries(raw).map(
    ([districtName, blocks]) => {
      const districtId = findDistrictId(districtName);
      const slots: DirectorySlot[] = [];
      for (const [blockNumber, schoolNames] of Object.entries(blocks)) {
        const blockId = `${districtId}-b${blockNumber}`;
        const blockLabel = `Block ${blockNumber}`;
        schoolNames.forEach((schoolName, schoolIndex) => {
          slots.push({ districtName, districtId, blockNumber, blockId, blockLabel, schoolName, schoolIndex });
        });
      }
      const rng = createRng(`school-directory-shuffle:${districtId}`);
      return shuffle(rng, slots);
    },
  );

  const selected: DirectorySlot[] = [];
  let cursor = 0;
  while (selected.length < totalAccounts) {
    const before = selected.length;
    for (const slots of perDistrictSlots) {
      if (selected.length >= totalAccounts) break;
      if (cursor < slots.length) selected.push(slots[cursor]);
    }
    if (selected.length === before) break;
    cursor += 1;
  }

  return selected.map((slot, i) => {
    const rng = createRng(`zoho-directory-account:${slot.blockId}:${slot.schoolIndex}`);
    const schoolSlug = slugify(slot.schoolName) || `school-${i}`;
    const statusRoll = rng();
    const status: ZohoAccountStatus =
      statusRoll > 0.92 ? "suspended" : statusRoll > 0.78 ? "pending" : "active";
    const daysAgo = randInt(rng, 0, 10);

    return {
      id: `dir-${slot.blockId}-${slot.schoolIndex}`,
      schoolName: slot.schoolName,
      districtId: slot.districtId,
      districtName: slot.districtName,
      blockId: slot.blockId,
      blockLabel: slot.blockLabel,
      loginEmail: `${schoolSlug}.${slot.blockNumber}@web.zohoclasses.in`,
      loginUrl: "https://web.zohoclasses.in/login/",
      environmentLabel: pick(rng, ENVIRONMENT_LABELS),
      status,
      lastVerifiedAt: new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000).toISOString(),
      region: "Tamil Nadu",
      mockAccessState: status === "active" ? "ready" : "simulated_redirect",
    } satisfies DirectorySchoolAccount;
  });
}
